######################################################################
# Automatically generated by qmake (3.0) Thu Jan 23 15:49:52 2014
######################################################################

TEMPLATE = app
TARGET = terrain
CONFIG += debug
INCLUDEPATH += . packages/noise/src
LIBS += -lSDL2 -lglut -lGLU -lGL 
OBJECTS_DIR = obj

SOURCES += \
    src/scene.cpp \
    src/main.cpp \
    src/terrainscene.cpp \
    packages/noise/src/noisegen.cpp \
    packages/noise/src/latlon.cpp \
    packages/noise/src/model/sphere.cpp \
    packages/noise/src/model/plane.cpp \
    packages/noise/src/model/line.cpp \
    packages/noise/src/model/cylinder.cpp \
    packages/noise/src/module/voronoi.cpp \
    packages/noise/src/module/turbulence.cpp \
    packages/noise/src/module/translatepoint.cpp \
    packages/noise/src/module/terrace.cpp \
    packages/noise/src/module/spheres.cpp \
    packages/noise/src/module/select.cpp \
    packages/noise/src/module/scalepoint.cpp \
    packages/noise/src/module/scalebias.cpp \
    packages/noise/src/module/rotatepoint.cpp \
    packages/noise/src/module/ridgedmulti.cpp \
    packages/noise/src/module/power.cpp \
    packages/noise/src/module/perlin.cpp \
    packages/noise/src/module/multiply.cpp \
    packages/noise/src/module/modulebase.cpp \
    packages/noise/src/module/min.cpp \
    packages/noise/src/module/max.cpp \
    packages/noise/src/module/invert.cpp \
    packages/noise/src/module/exponent.cpp \
    packages/noise/src/module/displace.cpp \
    packages/noise/src/module/cylinders.cpp \
    packages/noise/src/module/curve.cpp \
    packages/noise/src/module/const.cpp \
    packages/noise/src/module/clamp.cpp \
    packages/noise/src/module/checkerboard.cpp \
    packages/noise/src/module/cache.cpp \
    packages/noise/src/module/blend.cpp \
    packages/noise/src/module/billow.cpp \
    packages/noise/src/module/add.cpp \
    packages/noise/src/module/abs.cpp

HEADERS += \
    src/scene.h \
    src/terrainscene.h \
    packages/noise/src/vectortable.h \
    packages/noise/src/noisegen.h \
    packages/noise/src/noise.h \
    packages/noise/src/misc.h \
    packages/noise/src/mathconsts.h \
    packages/noise/src/latlon.h \
    packages/noise/src/interp.h \
    packages/noise/src/exception.h \
    packages/noise/src/basictypes.h \
    packages/noise/src/model/sphere.h \
    packages/noise/src/model/plane.h \
    packages/noise/src/model/model.h \
    packages/noise/src/model/line.h \
    packages/noise/src/model/cylinder.h \
    packages/noise/src/module/voronoi.h \
    packages/noise/src/module/turbulence.h \
    packages/noise/src/module/translatepoint.h \
    packages/noise/src/module/terrace.h \
    packages/noise/src/module/spheres.h \
    packages/noise/src/module/select.h \
    packages/noise/src/module/scalepoint.h \
    packages/noise/src/module/scalebias.h \
    packages/noise/src/module/rotatepoint.h \
    packages/noise/src/module/ridgedmulti.h \
    packages/noise/src/module/power.h \
    packages/noise/src/module/perlin.h \
    packages/noise/src/module/multiply.h \
    packages/noise/src/module/modulebase.h \
    packages/noise/src/module/module.h \
    packages/noise/src/module/min.h \
    packages/noise/src/module/max.h \
    packages/noise/src/module/invert.h \
    packages/noise/src/module/exponent.h \
    packages/noise/src/module/displace.h \
    packages/noise/src/module/cylinders.h \
    packages/noise/src/module/curve.h \
    packages/noise/src/module/const.h \
    packages/noise/src/module/clamp.h \
    packages/noise/src/module/checkerboard.h \
    packages/noise/src/module/cache.h \
    packages/noise/src/module/blend.h \
    packages/noise/src/module/billow.h \
    packages/noise/src/module/add.h \
    packages/noise/src/module/abs.h

OTHER_FILES += \
    README.txt

DISTFILES += \
    README.txt
