######################################################################
# Automatically generated by qmake (3.0) Thu Jan 23 15:49:52 2014
######################################################################

TEMPLATE = app
TARGET = cube
CONFIG += debug
INCLUDEPATH += . /usr/include packages/obj-0.1
LIBS += -lSDL2 -lglut -lGLU -lGL -lpng
OBJECTS_DIR = obj

SOURCES += src/main.cpp \
    src/scene.cpp \
    src/cubescene.cpp

HEADERS += \
    src/scene.h \
    src/cubescene.h
